/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.FileInputStream;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.apache.poi.xssf.usermodel.XSSFSheet;

/**
 *
 * @author luod1
 */
public class EditExcel extends javax.swing.JFrame {

    EditTeacher e = new EditTeacher();
    ArrayList<String> teachList = e.getTeacherList();

    ReadExcel readex = new ReadExcel();
    ArrayList<String> dayM12 = readex.getDayM12();
    ArrayList<String> dayM34 = readex.getDayM34();
    ArrayList<String> dayP56 = readex.getDayP56();
    ArrayList<String> dayP78 = readex.getDayP78();
    ArrayList<String> onlynameM12 = readex.getOnlynameM12();
    ArrayList<String> onlynameP56 = readex.getOnlynameP56();
    ArrayList<String> onlynameM34 = readex.getOnlynameM34();
    ArrayList<String> onlynameP78 = readex.getOnlynameP78();

    ArrayList<String> dayML12 = readex.getDayML12();
    ArrayList<String> dayPL56 = readex.getDayPL56();
    ArrayList<String> dayML34 = readex.getDayML34();
    ArrayList<String> dayPL78 = readex.getDayPL78();
    ArrayList<String> onlynameML12 = readex.getOnlynameML12();
    ArrayList<String> onlynamePL56 = readex.getOnlynamePL56();
    ArrayList<String> onlynameML34 = readex.getOnlynameML34();
    ArrayList<String> onlynamePL78 = readex.getOnlynamePL78();

    ArrayList<String> levels = readex.getLevels();
    ArrayList<String> levelName = readex.getLevelName();

    /**
     * Creates new form EditExcel
     */
    public EditExcel() {
        initComponents();
        jta_showTeacher.append(teachList.toString());
        jta_show.setLineWrap(true);
        jta_showTeacher.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jbt_editTeacher = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtf_level = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_showTeacher = new javax.swing.JTextArea();
        jrb_monday = new javax.swing.JRadioButton();
        jrb_wednesday = new javax.swing.JRadioButton();
        jrb_Thursday = new javax.swing.JRadioButton();
        jrb_friday = new javax.swing.JRadioButton();
        jrb_tuesday = new javax.swing.JRadioButton();
        jbt_onlyName = new javax.swing.JButton();
        jbt_allshow = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jta_show = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jcb_day = new javax.swing.JCheckBox();
        jcb_level = new javax.swing.JCheckBox();
        jbt_search = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("监考老师列表：");

        jbt_editTeacher.setText("Edit");
        jbt_editTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_editTeacherActionPerformed(evt);
            }
        });

        jLabel6.setText("Level: (20级,输入20)");

        jtf_level.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_levelActionPerformed(evt);
            }
        });

        jta_showTeacher.setEditable(false);
        jta_showTeacher.setColumns(20);
        jta_showTeacher.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jta_showTeacher.setRows(5);
        jScrollPane1.setViewportView(jta_showTeacher);

        jrb_monday.setText("星期一");
        jrb_monday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_mondayActionPerformed(evt);
            }
        });

        jrb_wednesday.setText("星期三");
        jrb_wednesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_wednesdayActionPerformed(evt);
            }
        });

        jrb_Thursday.setText("星期四");
        jrb_Thursday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_ThursdayActionPerformed(evt);
            }
        });

        jrb_friday.setText("星期五");
        jrb_friday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_fridayActionPerformed(evt);
            }
        });

        jrb_tuesday.setText("星期二");
        jrb_tuesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_tuesdayActionPerformed(evt);
            }
        });

        jbt_onlyName.setText("只显示名字");
        jbt_onlyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_onlyNameActionPerformed(evt);
            }
        });

        jbt_allshow.setText("显示所有");
        jbt_allshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_allshowActionPerformed(evt);
            }
        });

        jta_show.setEditable(false);
        jta_show.setColumns(20);
        jta_show.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jta_show.setRows(5);
        jScrollPane2.setViewportView(jta_show);

        jLabel1.setText("请勾选确认搜索条件 ");

        jcb_day.setText("勾选确认星期搜索");

        jcb_level.setText("勾选确认年级搜索");

        jbt_search.setText("搜索");
        jbt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_searchActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("请确认课表文件为excel格式，并且没有合并单元格！！");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbt_onlyName)
                            .addComponent(jbt_allshow))
                        .addGap(33, 33, 33))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(32, 32, 32)
                                        .addComponent(jtf_level, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrb_monday)
                                        .addGap(38, 38, 38)
                                        .addComponent(jrb_tuesday)
                                        .addGap(40, 40, 40)
                                        .addComponent(jrb_wednesday)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jrb_Thursday)
                                        .addGap(43, 43, 43)
                                        .addComponent(jrb_friday))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jcb_level)))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jbt_editTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                                        .addComponent(jbt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(156, 156, 156))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jcb_day)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(81, 81, 81))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jbt_editTeacher))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrb_monday)
                    .addComponent(jrb_tuesday)
                    .addComponent(jrb_wednesday)
                    .addComponent(jrb_Thursday)
                    .addComponent(jrb_friday)
                    .addComponent(jcb_day))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtf_level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_level)
                    .addComponent(jLabel1)
                    .addComponent(jbt_search))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbt_onlyName)
                        .addGap(43, 43, 43)
                        .addComponent(jbt_allshow)
                        .addGap(198, 198, 198))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(47, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jbt_editTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_editTeacherActionPerformed
        // TODO add your handling code here:
        new EditTeacher().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbt_editTeacherActionPerformed

    private void jrb_mondayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_mondayActionPerformed
        // TODO add your handling code here:
        if (jrb_monday.isSelected()) {
            jrb_Thursday.setSelected(false);
            jrb_friday.setSelected(false);
            jrb_tuesday.setSelected(false);
            jrb_wednesday.setSelected(false);
        }
    }//GEN-LAST:event_jrb_mondayActionPerformed

    private void jrb_tuesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_tuesdayActionPerformed
        // TODO add your handling code here:
        if (jrb_tuesday.isSelected()) {
            jrb_Thursday.setSelected(false);
            jrb_friday.setSelected(false);
            jrb_monday.setSelected(false);
            jrb_wednesday.setSelected(false);
        }
    }//GEN-LAST:event_jrb_tuesdayActionPerformed

    private void jrb_wednesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_wednesdayActionPerformed
        // TODO add your handling code here:
        if (jrb_wednesday.isSelected()) {
            jrb_Thursday.setSelected(false);
            jrb_friday.setSelected(false);
            jrb_monday.setSelected(false);
            jrb_tuesday.setSelected(false);
        }
    }//GEN-LAST:event_jrb_wednesdayActionPerformed

    private void jrb_ThursdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_ThursdayActionPerformed
        // TODO add your handling code here:
        if (jrb_Thursday.isSelected()) {
            jrb_tuesday.setSelected(false);
            jrb_friday.setSelected(false);
            jrb_monday.setSelected(false);
            jrb_wednesday.setSelected(false);
        }
    }//GEN-LAST:event_jrb_ThursdayActionPerformed

    private void jrb_fridayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_fridayActionPerformed
        // TODO add your handling code here:
        if (jrb_friday.isSelected()) {
            jrb_tuesday.setSelected(false);
            jrb_Thursday.setSelected(false);
            jrb_monday.setSelected(false);
            jrb_wednesday.setSelected(false);
        }
    }//GEN-LAST:event_jrb_fridayActionPerformed

    private void jbt_onlyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_onlyNameActionPerformed
        // TODO add your handling code here:
        ArrayList<String> nameML12 = readex.deleteDuplicates(onlynameML12);
        ArrayList<String> namePL56 = readex.deleteDuplicates(onlynamePL56);
        ArrayList<String> nameM12 = readex.deleteDuplicates(onlynameM12);
        ArrayList<String> nameP56 = readex.deleteDuplicates(onlynameP56);

        ArrayList<String> nameML34 = readex.deleteDuplicates(onlynameML34);
        ArrayList<String> namePL78 = readex.deleteDuplicates(onlynamePL78);
        ArrayList<String> nameM34 = readex.deleteDuplicates(onlynameM34);
        ArrayList<String> nameP78 = readex.deleteDuplicates(onlynameP78);

        ArrayList<String> LEVELname = readex.deleteDuplicates(levelName);

        if (jcb_day.isSelected()) {
            if (jcb_level.isSelected()) {
                jta_show.setText("");
                jta_show.append("上午1-2节：" + nameML12);
                jta_show.append("\n");
                jta_show.append("\n上午3-4节：" + nameML34);
                jta_show.append("\n");
                jta_show.append("\n下午5-6节：" + namePL56);
                jta_show.append("\n");
                jta_show.append("\n下午7-8节：" + namePL78);
            } else {
                jta_show.setText("");
                jta_show.append("上午1-2节：" + nameM12);
                jta_show.append("\n");
                jta_show.append("\n上午3-4节：" + nameM34);
                jta_show.append("\n");
                jta_show.append("\n下午5-6节：" + nameP56);
                jta_show.append("\n");
                jta_show.append("\n下午7-8节：" + nameP78);
            }

        } else {
            if (jcb_level.isSelected()) {
                jta_show.setText("");
                String level = jtf_level.getText();
                jta_show.append(level + "级: ");
                jta_show.append("\n" + LEVELname);
            }
        }


    }//GEN-LAST:event_jbt_onlyNameActionPerformed

    private void jbt_allshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_allshowActionPerformed
        // TODO add your handling code here:
        if (jcb_day.isSelected()) {
            if (jcb_level.isSelected()) {
                jta_show.setText("");
                jta_show.append("上午1-2节：" + dayML12);
                jta_show.append("\n");
                jta_show.append("\n上午3-4节：" + dayML34);
                jta_show.append("\n");
                jta_show.append("\n下午5-6节：" + dayPL56);
                jta_show.append("\n");
                jta_show.append("\n下午7-8节：" + dayPL78);
            } else {
                jta_show.setText("");
                jta_show.append("上午1-2节：" + dayM12);
                jta_show.append("\n");
                jta_show.append("\n上午3-4节：" + dayM34);
                jta_show.append("\n");
                jta_show.append("\n下午5-6节：" + dayP56);
                jta_show.append("\n");
                jta_show.append("\n下午7-8节：" + dayP78);
            }
        } else {
            if (jcb_level.isSelected()) {
                jta_show.setText("");
                String level = jtf_level.getText();
                jta_show.append(level + "级: ");
                jta_show.append("\n" + levels);
            }
        }
    }//GEN-LAST:event_jbt_allshowActionPerformed

    private void jtf_levelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_levelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_levelActionPerformed

    private void jbt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_searchActionPerformed
        // TODO add your handling code here:
        try {

            dayML12.clear();
            dayPL56.clear();
            dayM12.clear();
            dayP56.clear();
            dayML34.clear();
            dayPL78.clear();
            dayM34.clear();
            dayP78.clear();

            onlynameML12.clear();
            onlynamePL56.clear();
            onlynameM12.clear();
            onlynameP56.clear();
            onlynameML34.clear();
            onlynamePL78.clear();
            onlynameM34.clear();
            onlynameP78.clear();
            levels.clear();
            levelName.clear();
            FileInputStream inputstream = readex.getFile();
            XSSFSheet sheet = readex.readExcel(inputstream);
            int rows = sheet.getLastRowNum();
            int cols = sheet.getRow(1).getLastCellNum();
            if (jcb_day.isSelected()) {
                if (jcb_level.isSelected() == false) {
                    if (jrb_monday.isSelected()) {
                        String day = "星期一";
                        readex.SearchDay(teachList, rows, cols, sheet, day);
                    } else if (jrb_tuesday.isSelected()) {
                        String day = "星期二";
                        readex.SearchDay(teachList, rows, cols, sheet, day);
                    } else if (jrb_wednesday.isSelected()) {
                        String day = "星期三";
                        readex.SearchDay(teachList, rows, cols, sheet, day);
                    } else if (jrb_Thursday.isSelected()) {
                        String day = "星期四";
                        readex.SearchDay(teachList, rows, cols, sheet, day);
                    } else if (jrb_friday.isSelected()) {
                        String day = "星期五";
                        readex.SearchDay(teachList, rows, cols, sheet, day);
                    } else {
                        JOptionPane.showMessageDialog(null, "Hello，你没有选择星期几", "message", JOptionPane.OK_CANCEL_OPTION);
                    }
                    jta_show.setText("");

                    jta_show.append("上午1-2节：" + dayM12);
                    jta_show.append("\n");
                    jta_show.append("\n上午3-4节：" + dayM34);
                    jta_show.append("\n");
                    jta_show.append("\n下午5-6节：" + dayP56);
                    jta_show.append("\n");
                    jta_show.append("\n下午7-8节：" + dayP78);

                } else {
                    String level = jtf_level.getText();
                    if (jrb_monday.isSelected()) {
                        String day = "星期一";
                        readex.SearchDayLevel(teachList, rows, cols, sheet, day, level);
                    } else if (jrb_tuesday.isSelected()) {
                        String day = "星期二";
                        readex.SearchDayLevel(teachList, rows, cols, sheet, day, level);
                    } else if (jrb_wednesday.isSelected()) {
                        String day = "星期三";
                        readex.SearchDayLevel(teachList, rows, cols, sheet, day, level);
                    } else if (jrb_Thursday.isSelected()) {
                        String day = "星期四";
                        readex.SearchDayLevel(teachList, rows, cols, sheet, day, level);
                    } else if (jrb_friday.isSelected()) {
                        String day = "星期五";
                        readex.SearchDayLevel(teachList, rows, cols, sheet, day, level);
                    } else {
                        JOptionPane.showMessageDialog(null, "Hello，你没有选择星期几", "message", JOptionPane.OK_CANCEL_OPTION);
                    }
                    jta_show.setText("");
                    jta_show.append("上午1-2节：" + dayML12);
                    jta_show.append("\n");
                    jta_show.append("\n上午3-4节：" + dayML34);
                    jta_show.append("\n");
                    jta_show.append("\n下午5-6节：" + dayPL56);
                    jta_show.append("\n");
                    jta_show.append("\n下午7-8节：" + dayPL78);

                }
            } else {
                if (jcb_level.isSelected()) {
                    String level = jtf_level.getText();
                    if (!"".equals(level)) {
                        readex.SearchLevel(teachList, rows, cols, sheet, level);

                        jta_show.setText("");
                        jta_show.append(level + "级: " + levels);

                    } else {
                        JOptionPane.showMessageDialog(null, "Hello,请输入年级", "message", JOptionPane.OK_CANCEL_OPTION);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Hello,？？？你需要搜索啥？你也啥也没有选择", "message", JOptionPane.OK_CANCEL_OPTION);
                }
            }

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Hello,无效", "message", JOptionPane.OK_CANCEL_OPTION);
            //Logger.getLogger(EditExcel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbt_searchActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EditExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EditExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EditExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EditExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EditExcel().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbt_allshow;
    private javax.swing.JButton jbt_editTeacher;
    private javax.swing.JButton jbt_onlyName;
    private javax.swing.JButton jbt_search;
    private javax.swing.JCheckBox jcb_day;
    private javax.swing.JCheckBox jcb_level;
    private javax.swing.JRadioButton jrb_Thursday;
    private javax.swing.JRadioButton jrb_friday;
    private javax.swing.JRadioButton jrb_monday;
    private javax.swing.JRadioButton jrb_tuesday;
    private javax.swing.JRadioButton jrb_wednesday;
    private javax.swing.JTextArea jta_show;
    private javax.swing.JTextArea jta_showTeacher;
    private javax.swing.JTextField jtf_level;
    // End of variables declaration//GEN-END:variables
}
