/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author luod1
 *
 */
public class EditTeacher extends javax.swing.JFrame {

    public static ArrayList<String> TeacherList = new ArrayList<>();

    public ArrayList<String> getTeacherList() {
        //System.out.print(TeacherList.toString());
        return TeacherList;
    }

    /**
     * Creates new form EditTeacher
     */
    public EditTeacher() {
        initComponents();
//        TeacherList.add("林颖");
//        TeacherList.add("刘畅");
//        TeacherList.add("王媛");
//        TeacherList.add("李发金");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtf_TeacherName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbt_addTeacher = new javax.swing.JButton();
        jbt_TeacherSubmit = new javax.swing.JButton();
        jbt_deleteCourse = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlist_teacher = new javax.swing.JList<>();
        jbt_deleteAllTeacher = new javax.swing.JButton();
        jbt_txt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Name: ");

        jtf_TeacherName.setText("程修远");
        jtf_TeacherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_TeacherNameActionPerformed(evt);
            }
        });

        jbt_addTeacher.setText("add");
        jbt_addTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_addTeacherActionPerformed(evt);
            }
        });

        jbt_TeacherSubmit.setText("Submit");
        jbt_TeacherSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_TeacherSubmitActionPerformed(evt);
            }
        });

        jbt_deleteCourse.setText("delete");
        jbt_deleteCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_deleteCourseActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setText("Edit Teacher");

        jlist_teacher.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jlist_teacher);

        jbt_deleteAllTeacher.setText("delete all");
        jbt_deleteAllTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_deleteAllTeacherActionPerformed(evt);
            }
        });

        jbt_txt.setText("上传txt文件");
        jbt_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_txtActionPerformed(evt);
            }
        });

        jLabel2.setText("通过txt文件加入名单");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbt_deleteCourse)
                            .addComponent(jbt_deleteAllTeacher)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_TeacherName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_addTeacher)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbt_txt)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jbt_TeacherSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbt_addTeacher, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtf_TeacherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbt_txt)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jbt_deleteCourse)
                                .addGap(40, 40, 40)
                                .addComponent(jbt_deleteAllTeacher)))
                        .addGap(0, 63, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbt_TeacherSubmit)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_TeacherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_TeacherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_TeacherNameActionPerformed

    DefaultListModel listdisplay = new DefaultListModel();
    private void jbt_addTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_addTeacherActionPerformed
        // get teacher name
        String name = jtf_TeacherName.getText();
        //Teachers t = new Teachers(name);
        TeacherList.add(name);

        listdisplay.addElement(name);

        jlist_teacher.setModel(listdisplay);

    }//GEN-LAST:event_jbt_addTeacherActionPerformed

    private void jbt_deleteAllTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_deleteAllTeacherActionPerformed
        // TODO add your handling code here:
        TeacherList.clear();
        listdisplay.removeAllElements();
    }//GEN-LAST:event_jbt_deleteAllTeacherActionPerformed

    private void jbt_deleteCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_deleteCourseActionPerformed
        // TODO add your handling code here:
        int i = jlist_teacher.getSelectedIndex();
        listdisplay.removeElementAt(i);
        TeacherList.remove(i);

    }//GEN-LAST:event_jbt_deleteCourseActionPerformed

    private void jbt_TeacherSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_TeacherSubmitActionPerformed
        // TODO add your handling code here:
        //System.out.print(TeacherList.toString());
        new EditExcel().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbt_TeacherSubmitActionPerformed

    private void jbt_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_txtActionPerformed
        // TODO add your handling code here:
        TeacherList.clear();
        listdisplay.removeAllElements();
        TeacherList = readTextFile();
        for (String n : TeacherList) {
            listdisplay.addElement(n);
        }
        jlist_teacher.setModel(listdisplay);
    }//GEN-LAST:event_jbt_txtActionPerformed

    public ArrayList<String> readTextFile() {
        ArrayList<String> checkins = new ArrayList();
        ArrayList<String> checkin = new ArrayList();
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("TEXT FILES", "txt", "text");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(null);

        BufferedReader br;
        try {
            br = new BufferedReader(new InputStreamReader(new FileInputStream(chooser.getSelectedFile()), "UTF-8"));
            String line = "";
            // StringBuilder sb = new StringBuilder();

            line = br.readLine();
            while (line != null) {
                checkins.add(line);
                line = br.readLine();
            }

            for (String n : checkins) {
                if (!"".equals(n)) {
                    checkin.add(n);
                    //int i = checkins.indexOf(n);
                    //checkins.remove(i);
                    //System.out.print("1");
                }
            }
            ReadExcel ex = new ReadExcel();
            checkin = ex.deleteDuplicates(checkin);

            return checkin;
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Hello,无效", "message", JOptionPane.OK_CANCEL_OPTION);
        }
            return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditTeacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbt_TeacherSubmit;
    private javax.swing.JButton jbt_addTeacher;
    private javax.swing.JButton jbt_deleteAllTeacher;
    private javax.swing.JButton jbt_deleteCourse;
    private javax.swing.JButton jbt_txt;
    private javax.swing.JList<String> jlist_teacher;
    private javax.swing.JTextField jtf_TeacherName;
    // End of variables declaration//GEN-END:variables
}
